export const shortList = [
  {Country: 'Cape Verde', ISO2: 'CV', Slug: 'cape-verde'},
  {Country: 'Equatorial Guinea', ISO2: 'GQ', Slug: 'equatorial-guinea'},
  {Country: 'Kenya', ISO2: 'KE', Slug: 'kenya'},
  {Country: 'Poland', ISO2: 'PL', Slug: 'poland'},
  {Country: 'Switzerland', ISO2: 'CH', Slug: 'switzerland'},
  {Country: 'Uzbekistan', ISO2: 'UZ', Slug: 'uzbekistan'},
  {Country: 'Sudan', ISO2: 'SD', Slug: 'sudan'},
  {Country: 'Djibouti', ISO2: 'DJ', Slug: 'djibouti'},
]

export const list = [
  {Country: 'Cape Verde', ISO2: 'CV', Slug: 'cape-verde'},
  {Country: 'Equatorial Guinea', ISO2: 'GQ', Slug: 'equatorial-guinea'},
  {Country: 'Kenya', ISO2: 'KE', Slug: 'kenya'},
  {Country: 'Poland', ISO2: 'PL', Slug: 'poland'},
  {Country: 'Switzerland', ISO2: 'CH', Slug: 'switzerland'},
  {Country: 'Uzbekistan', ISO2: 'UZ', Slug: 'uzbekistan'},
  {Country: 'Sudan', ISO2: 'SD', Slug: 'sudan'},
  {Country: 'Djibouti', ISO2: 'DJ', Slug: 'djibouti'},
  {
    Country: 'Holy See (Vatican City State)',
    ISO2: 'VA',
    Slug: 'holy-see-vatican-city-state',
  },
  {Country: 'Libya', ISO2: 'LY', Slug: 'libya'},
  {Country: 'Austria', ISO2: 'AT', Slug: 'austria'},
  {Country: 'Mauritius', ISO2: 'MU', Slug: 'mauritius'},
  {Country: 'Mexico', ISO2: 'MX', Slug: 'mexico'},
  {Country: 'Papua New Guinea', ISO2: 'PG', Slug: 'papua-new-guinea'},
  {Country: 'Saint-Barthélemy', ISO2: 'BL', Slug: 'saint-barthélemy'},
  {Country: 'Slovenia', ISO2: 'SI', Slug: 'slovenia'},
  {
    Country: 'US Minor Outlying Islands',
    ISO2: 'UM',
    Slug: 'us-minor-outlying-islands',
  },
  {Country: 'Greece', ISO2: 'GR', Slug: 'greece'},
  {Country: 'Latvia', ISO2: 'LV', Slug: 'latvia'},
  {Country: 'South Sudan', ISO2: 'SS', Slug: 'south-sudan'},
  {Country: 'Tajikistan', ISO2: 'TJ', Slug: 'tajikistan'},
  {
    Country: 'Turks and Caicos Islands',
    ISO2: 'TC',
    Slug: 'turks-and-caicos-islands',
  },
  {Country: 'Uruguay', ISO2: 'UY', Slug: 'uruguay'},
  {Country: 'Vanuatu', ISO2: 'VU', Slug: 'vanuatu'},
  {Country: 'Czech Republic', ISO2: 'CZ', Slug: 'czech-republic'},
  {Country: 'Congo (Brazzaville)', ISO2: 'CG', Slug: 'congo-brazzaville'},
  {Country: 'Bahrain', ISO2: 'BH', Slug: 'bahrain'},
  {
    Country: 'Central African Republic',
    ISO2: 'CF',
    Slug: 'central-african-republic',
  },
  {Country: 'Hungary', ISO2: 'HU', Slug: 'hungary'},
  {Country: 'Lithuania', ISO2: 'LT', Slug: 'lithuania'},
  {Country: 'Samoa', ISO2: 'WS', Slug: 'samoa'},
  {Country: 'Cameroon', ISO2: 'CM', Slug: 'cameroon'},
  {Country: 'Faroe Islands', ISO2: 'FO', Slug: 'faroe-islands'},
  {Country: 'Singapore', ISO2: 'SG', Slug: 'singapore'},
  {Country: 'Syrian Arab Republic (Syria)', ISO2: 'SY', Slug: 'syria'},
  {Country: 'United States of America', ISO2: 'US', Slug: 'united-states'},
  {Country: 'China', ISO2: 'CN', Slug: 'china'},
  {Country: 'Guatemala', ISO2: 'GT', Slug: 'guatemala'},
  {Country: 'Seychelles', ISO2: 'SC', Slug: 'seychelles'},
  {Country: 'Mayotte', ISO2: 'YT', Slug: 'mayotte'},
  {Country: 'France', ISO2: 'FR', Slug: 'france'},
  {Country: 'Iran, Islamic Republic of', ISO2: 'IR', Slug: 'iran'},
  {Country: 'Aruba', ISO2: 'AW', Slug: 'aruba'},
  {Country: 'Canada', ISO2: 'CA', Slug: 'canada'},
  {Country: 'Georgia', ISO2: 'GE', Slug: 'georgia'},
  {
    Country: 'Heard and Mcdonald Islands',
    ISO2: 'HM',
    Slug: 'heard-and-mcdonald-islands',
  },
  {Country: 'Bahamas', ISO2: 'BS', Slug: 'bahamas'},
  {Country: 'Togo', ISO2: 'TG', Slug: 'togo'},
  {Country: 'Greenland', ISO2: 'GL', Slug: 'greenland'},
  {Country: 'Luxembourg', ISO2: 'LU', Slug: 'luxembourg'},
  {Country: 'Paraguay', ISO2: 'PY', Slug: 'paraguay'},
  {Country: 'United Arab Emirates', ISO2: 'AE', Slug: 'united-arab-emirates'},
  {Country: 'French Polynesia', ISO2: 'PF', Slug: 'french-polynesia'},
  {Country: 'Bhutan', ISO2: 'BT', Slug: 'bhutan'},
  {Country: 'Cambodia', ISO2: 'KH', Slug: 'cambodia'},
  {Country: 'Mali', ISO2: 'ML', Slug: 'mali'},
  {Country: 'Rwanda', ISO2: 'RW', Slug: 'rwanda'},
  {Country: 'South Africa', ISO2: 'ZA', Slug: 'south-africa'},
  {Country: 'Guinea-Bissau', ISO2: 'GW', Slug: 'guinea-bissau'},
  {Country: 'Korea (South)', ISO2: 'KR', Slug: 'korea-south'},
  {Country: 'Mozambique', ISO2: 'MZ', Slug: 'mozambique'},
  {Country: 'Solomon Islands', ISO2: 'SB', Slug: 'solomon-islands'},
  {Country: 'Angola', ISO2: 'AO', Slug: 'angola'},
  {Country: 'Japan', ISO2: 'JP', Slug: 'japan'},
  {Country: 'Liberia', ISO2: 'LR', Slug: 'liberia'},
  {Country: 'Brazil', ISO2: 'BR', Slug: 'brazil'},
  {Country: 'Brunei Darussalam', ISO2: 'BN', Slug: 'brunei'},
  {Country: 'Guadeloupe', ISO2: 'GP', Slug: 'guadeloupe'},
  {Country: 'American Samoa', ISO2: 'AS', Slug: 'american-samoa'},
  {Country: 'Burundi', ISO2: 'BI', Slug: 'burundi'},
  {Country: 'Denmark', ISO2: 'DK', Slug: 'denmark'},
  {Country: 'French Guiana', ISO2: 'GF', Slug: 'french-guiana'},
  {Country: 'Western Sahara', ISO2: 'EH', Slug: 'western-sahara'},
  {Country: 'Afghanistan', ISO2: 'AF', Slug: 'afghanistan'},
  {Country: 'Montenegro', ISO2: 'ME', Slug: 'montenegro'},
  {Country: 'Nauru', ISO2: 'NR', Slug: 'nauru'},
  {Country: 'Taiwan, Republic of China', ISO2: 'TW', Slug: 'taiwan'},
  {Country: 'Bermuda', ISO2: 'BM', Slug: 'bermuda'},
  {Country: 'Indonesia', ISO2: 'ID', Slug: 'indonesia'},
  {Country: 'Lao PDR', ISO2: 'LA', Slug: 'lao-pdr'},
  {Country: 'New Caledonia', ISO2: 'NC', Slug: 'new-caledonia'},
  {Country: 'Cuba', ISO2: 'CU', Slug: 'cuba'},
  {Country: 'Netherlands Antilles', ISO2: 'AN', Slug: 'netherlands-antilles'},
  {Country: 'Peru', ISO2: 'PE', Slug: 'peru'},
  {Country: 'Saudi Arabia', ISO2: 'SA', Slug: 'saudi-arabia'},
  {Country: 'Benin', ISO2: 'BJ', Slug: 'benin'},
  {Country: 'Comoros', ISO2: 'KM', Slug: 'comoros'},
  {Country: 'Dominican Republic', ISO2: 'DO', Slug: 'dominican-republic'},
  {Country: 'India', ISO2: 'IN', Slug: 'india'},
  {Country: 'Nicaragua', ISO2: 'NI', Slug: 'nicaragua'},
  {Country: 'Philippines', ISO2: 'PH', Slug: 'philippines'},
  {Country: 'ALA Aland Islands', ISO2: 'AX', Slug: 'ala-aland-islands'},
  {Country: 'Guinea', ISO2: 'GN', Slug: 'guinea'},
  {
    Country: 'Northern Mariana Islands',
    ISO2: 'MP',
    Slug: 'northern-mariana-islands',
  },
  {Country: 'Estonia', ISO2: 'EE', Slug: 'estonia'},
  {Country: 'Venezuela (Bolivarian Republic)', ISO2: 'VE', Slug: 'venezuela'},
  {
    Country: 'Falkland Islands (Malvinas)',
    ISO2: 'FK',
    Slug: 'falkland-islands-malvinas',
  },
  {Country: 'Chad', ISO2: 'TD', Slug: 'chad'},
  {Country: 'Christmas Island', ISO2: 'CX', Slug: 'christmas-island'},
  {Country: 'Colombia', ISO2: 'CO', Slug: 'colombia'},
  {Country: 'Thailand', ISO2: 'TH', Slug: 'thailand'},
  {Country: 'Tunisia', ISO2: 'TN', Slug: 'tunisia'},
  {Country: 'Bolivia', ISO2: 'BO', Slug: 'bolivia'},
  {Country: 'Mongolia', ISO2: 'MN', Slug: 'mongolia'},
  {Country: 'Pakistan', ISO2: 'PK', Slug: 'pakistan'},
  {Country: 'Swaziland', ISO2: 'SZ', Slug: 'swaziland'},
  {Country: 'Honduras', ISO2: 'HN', Slug: 'honduras'},
  {Country: 'Liechtenstein', ISO2: 'LI', Slug: 'liechtenstein'},
  {Country: 'Macedonia, Republic of', ISO2: 'MK', Slug: 'macedonia'},
  {Country: 'Puerto Rico', ISO2: 'PR', Slug: 'puerto-rico'},
  {Country: 'Ireland', ISO2: 'IE', Slug: 'ireland'},
  {
    Country: 'Bosnia and Herzegovina',
    ISO2: 'BA',
    Slug: 'bosnia-and-herzegovina',
  },
  {Country: 'Cayman Islands', ISO2: 'KY', Slug: 'cayman-islands'},
  {Country: "Côte d'Ivoire", ISO2: 'CI', Slug: 'cote-divoire'},
  {Country: 'Hong Kong, SAR China', ISO2: 'HK', Slug: 'hong-kong-sar-china'},
  {Country: 'Jamaica', ISO2: 'JM', Slug: 'jamaica'},
  {Country: 'Myanmar', ISO2: 'MM', Slug: 'myanmar'},
  {Country: 'Zambia', ISO2: 'ZM', Slug: 'zambia'},
  {Country: 'Armenia', ISO2: 'AM', Slug: 'armenia'},
  {Country: 'Egypt', ISO2: 'EG', Slug: 'egypt'},
  {Country: 'Macao, SAR China', ISO2: 'MO', Slug: 'macao-sar-china'},
  {
    Country: 'Sao Tome and Principe',
    ISO2: 'ST',
    Slug: 'sao-tome-and-principe',
  },
  {Country: 'Fiji', ISO2: 'FJ', Slug: 'fiji'},
  {Country: 'Martinique', ISO2: 'MQ', Slug: 'martinique'},
  {
    Country: 'Micronesia, Federated States of',
    ISO2: 'FM',
    Slug: 'micronesia',
  },
  {Country: 'Senegal', ISO2: 'SN', Slug: 'senegal'},
  {Country: 'Serbia', ISO2: 'RS', Slug: 'serbia'},
  {Country: 'Bangladesh', ISO2: 'BD', Slug: 'bangladesh'},
  {Country: 'Belgium', ISO2: 'BE', Slug: 'belgium'},
  {Country: 'Eritrea', ISO2: 'ER', Slug: 'eritrea'},
  {Country: 'Italy', ISO2: 'IT', Slug: 'italy'},
  {Country: 'Namibia', ISO2: 'NA', Slug: 'namibia'},
  {
    Country: 'Saint Kitts and Nevis',
    ISO2: 'KN',
    Slug: 'saint-kitts-and-nevis',
  },
  {Country: 'Lebanon', ISO2: 'LB', Slug: 'lebanon'},
  {Country: 'Norway', ISO2: 'NO', Slug: 'norway'},
  {Country: 'Saint Lucia', ISO2: 'LC', Slug: 'saint-lucia'},
  {Country: 'Antigua and Barbuda', ISO2: 'AG', Slug: 'antigua-and-barbuda'},
  {Country: 'Guyana', ISO2: 'GY', Slug: 'guyana'},
  {Country: 'Andorra', ISO2: 'AD', Slug: 'andorra'},
  {Country: 'Gibraltar', ISO2: 'GI', Slug: 'gibraltar'},
  {Country: 'Jordan', ISO2: 'JO', Slug: 'jordan'},
  {Country: 'Cyprus', ISO2: 'CY', Slug: 'cyprus'},
  {
    Country: 'British Virgin Islands',
    ISO2: 'VG',
    Slug: 'british-virgin-islands',
  },
  {Country: 'Sierra Leone', ISO2: 'SL', Slug: 'sierra-leone'},
  {Country: 'Antarctica', ISO2: 'AQ', Slug: 'antarctica'},
  {Country: 'Panama', ISO2: 'PA', Slug: 'panama'},
  {Country: 'Sri Lanka', ISO2: 'LK', Slug: 'sri-lanka'},
  {Country: 'Turkmenistan', ISO2: 'TM', Slug: 'turkmenistan'},
  {Country: 'Anguilla', ISO2: 'AI', Slug: 'anguilla'},
  {
    Country: 'French Southern Territories',
    ISO2: 'TF',
    Slug: 'french-southern-territories',
  },
  {Country: 'Israel', ISO2: 'IL', Slug: 'israel'},
  {Country: 'Suriname', ISO2: 'SR', Slug: 'suriname'},
  {Country: 'Sweden', ISO2: 'SE', Slug: 'sweden'},
  {Country: 'Turkey', ISO2: 'TR', Slug: 'turkey'},
  {Country: 'Iraq', ISO2: 'IQ', Slug: 'iraq'},
  {Country: 'Norfolk Island', ISO2: 'NF', Slug: 'norfolk-island'},
  {Country: 'Zimbabwe', ISO2: 'ZW', Slug: 'zimbabwe'},
  {Country: 'Belize', ISO2: 'BZ', Slug: 'belize'},
  {Country: 'Bulgaria', ISO2: 'BG', Slug: 'bulgaria'},
  {Country: 'Ecuador', ISO2: 'EC', Slug: 'ecuador'},
  {Country: 'Iceland', ISO2: 'IS', Slug: 'iceland'},
  {Country: 'Pitcairn', ISO2: 'PN', Slug: 'pitcairn'},
  {Country: 'Portugal', ISO2: 'PT', Slug: 'portugal'},
  {Country: 'Guam', ISO2: 'GU', Slug: 'guam'},
  {Country: 'Kyrgyzstan', ISO2: 'KG', Slug: 'kyrgyzstan'},
  {Country: 'Qatar', ISO2: 'QA', Slug: 'qatar'},
  {
    Country: 'Cocos (Keeling) Islands',
    ISO2: 'CC',
    Slug: 'cocos-keeling-islands',
  },
  {Country: 'Gambia', ISO2: 'GM', Slug: 'gambia'},
  {Country: 'Kiribati', ISO2: 'KI', Slug: 'kiribati'},
  {Country: 'Madagascar', ISO2: 'MG', Slug: 'madagascar'},
  {
    Country: 'Saint-Martin (French part)',
    ISO2: 'MF',
    Slug: 'saint-martin-french-part',
  },
  {Country: 'Tokelau', ISO2: 'TK', Slug: 'tokelau'},
  {Country: 'Barbados', ISO2: 'BB', Slug: 'barbados'},
  {Country: 'Algeria', ISO2: 'DZ', Slug: 'algeria'},
  {Country: 'Chile', ISO2: 'CL', Slug: 'chile'},
  {Country: 'Jersey', ISO2: 'JE', Slug: 'jersey'},
  {Country: 'Kazakhstan', ISO2: 'KZ', Slug: 'kazakhstan'},
  {Country: 'Palestinian Territory', ISO2: 'PS', Slug: 'palestine'},
  {Country: 'Tuvalu', ISO2: 'TV', Slug: 'tuvalu'},
  {Country: 'New Zealand', ISO2: 'NZ', Slug: 'new-zealand'},
  {Country: 'Somalia', ISO2: 'SO', Slug: 'somalia'},
  {Country: 'Cook Islands', ISO2: 'CK', Slug: 'cook-islands'},
  {Country: 'Croatia', ISO2: 'HR', Slug: 'croatia'},
  {Country: 'Niger', ISO2: 'NE', Slug: 'niger'},
  {Country: 'Niue', ISO2: 'NU', Slug: 'niue'},
  {Country: 'Trinidad and Tobago', ISO2: 'TT', Slug: 'trinidad-and-tobago'},
  {Country: 'Ukraine', ISO2: 'UA', Slug: 'ukraine'},
  {Country: 'El Salvador', ISO2: 'SV', Slug: 'el-salvador'},
  {Country: 'Costa Rica', ISO2: 'CR', Slug: 'costa-rica'},
  {Country: 'Kuwait', ISO2: 'KW', Slug: 'kuwait'},
  {Country: 'Netherlands', ISO2: 'NL', Slug: 'netherlands'},
  {
    Country: 'Wallis and Futuna Islands',
    ISO2: 'WF',
    Slug: 'wallis-and-futuna-islands',
  },
  {Country: 'Yemen', ISO2: 'YE', Slug: 'yemen'},
  {Country: 'Botswana', ISO2: 'BW', Slug: 'botswana'},
  {Country: 'Marshall Islands', ISO2: 'MH', Slug: 'marshall-islands'},
  {Country: 'Oman', ISO2: 'OM', Slug: 'oman'},
  {Country: 'Haiti', ISO2: 'HT', Slug: 'haiti'},
  {Country: 'Ethiopia', ISO2: 'ET', Slug: 'ethiopia'},
  {Country: 'Gabon', ISO2: 'GA', Slug: 'gabon'},
  {Country: 'Malaysia', ISO2: 'MY', Slug: 'malaysia'},
  {Country: 'Mauritania', ISO2: 'MR', Slug: 'mauritania'},
  {Country: 'Morocco', ISO2: 'MA', Slug: 'morocco'},
  {Country: 'Guernsey', ISO2: 'GG', Slug: 'guernsey'},
  {Country: 'Nepal', ISO2: 'NP', Slug: 'nepal'},
  {
    Country: 'Saint Pierre and Miquelon',
    ISO2: 'PM',
    Slug: 'saint-pierre-and-miquelon',
  },
  {
    Country: 'South Georgia and the South Sandwich Islands',
    ISO2: 'GS',
    Slug: 'south-georgia-and-the-south-sandwich-islands',
  },
  {Country: 'Congo (Kinshasa)', ISO2: 'CD', Slug: 'congo-kinshasa'},
  {Country: 'Finland', ISO2: 'FI', Slug: 'finland'},
  {Country: 'Tonga', ISO2: 'TO', Slug: 'tonga'},
  {Country: 'United Kingdom', ISO2: 'GB', Slug: 'united-kingdom'},
  {
    Country: 'British Indian Ocean Territory',
    ISO2: 'IO',
    Slug: 'british-indian-ocean-territory',
  },
  {Country: 'Bouvet Island', ISO2: 'BV', Slug: 'bouvet-island'},
  {Country: 'Germany', ISO2: 'DE', Slug: 'germany'},
  {Country: 'Isle of Man', ISO2: 'IM', Slug: 'isle-of-man'},
  {Country: 'Maldives', ISO2: 'MV', Slug: 'maldives'},
  {Country: 'Montserrat', ISO2: 'MS', Slug: 'montserrat'},
  {Country: 'Russian Federation', ISO2: 'RU', Slug: 'russia'},
  {Country: 'San Marino', ISO2: 'SM', Slug: 'san-marino'},
  {Country: 'Viet Nam', ISO2: 'VN', Slug: 'vietnam'},
  {Country: 'Dominica', ISO2: 'DM', Slug: 'dominica'},
  {Country: 'Belarus', ISO2: 'BY', Slug: 'belarus'},
  {Country: 'Ghana', ISO2: 'GH', Slug: 'ghana'},
  {Country: 'Nigeria', ISO2: 'NG', Slug: 'nigeria'},
  {Country: 'Saint Helena', ISO2: 'SH', Slug: 'saint-helena'},
  {Country: 'Spain', ISO2: 'ES', Slug: 'spain'},
  {Country: 'Slovakia', ISO2: 'SK', Slug: 'slovakia'},
  {Country: 'Korea (North)', ISO2: 'KP', Slug: 'korea-north'},
  {Country: 'Albania', ISO2: 'AL', Slug: 'albania'},
  {Country: 'Réunion', ISO2: 'RE', Slug: 'réunion'},
  {Country: 'Republic of Kosovo', ISO2: 'XK', Slug: 'kosovo'},
  {Country: 'Timor-Leste', ISO2: 'TL', Slug: 'timor-leste'},
  {Country: 'Burkina Faso', ISO2: 'BF', Slug: 'burkina-faso'},
  {Country: 'Grenada', ISO2: 'GD', Slug: 'grenada'},
  {Country: 'Palau', ISO2: 'PW', Slug: 'palau'},
  {
    Country: 'Saint Vincent and Grenadines',
    ISO2: 'VC',
    Slug: 'saint-vincent-and-the-grenadines',
  },
  {Country: 'Tanzania, United Republic of', ISO2: 'TZ', Slug: 'tanzania'},
  {Country: 'Malta', ISO2: 'MT', Slug: 'malta'},
  {Country: 'Monaco', ISO2: 'MC', Slug: 'monaco'},
  {Country: 'Uganda', ISO2: 'UG', Slug: 'uganda'},
  {Country: 'Virgin Islands, US', ISO2: 'VI', Slug: 'virgin-islands'},
  {Country: 'Lesotho', ISO2: 'LS', Slug: 'lesotho'},
  {Country: 'Azerbaijan', ISO2: 'AZ', Slug: 'azerbaijan'},
  {Country: 'Malawi', ISO2: 'MW', Slug: 'malawi'},
  {Country: 'Moldova', ISO2: 'MD', Slug: 'moldova'},
  {Country: 'Romania', ISO2: 'RO', Slug: 'romania'},
  {
    Country: 'Svalbard and Jan Mayen Islands',
    ISO2: 'SJ',
    Slug: 'svalbard-and-jan-mayen-islands',
  },
  {Country: 'Argentina', ISO2: 'AR', Slug: 'argentina'},
  {Country: 'Australia', ISO2: 'AU', Slug: 'australia'},
  {Country: 'Cape Verde', ISO2: 'CV', Slug: 'cape-verde'},
  {Country: 'Equatorial Guinea', ISO2: 'GQ', Slug: 'equatorial-guinea'},
  {Country: 'Kenya', ISO2: 'KE', Slug: 'kenya'},
  {Country: 'Poland', ISO2: 'PL', Slug: 'poland'},
  {Country: 'Switzerland', ISO2: 'CH', Slug: 'switzerland'},
  {Country: 'Uzbekistan', ISO2: 'UZ', Slug: 'uzbekistan'},
  {Country: 'Sudan', ISO2: 'SD', Slug: 'sudan'},
  {Country: 'Djibouti', ISO2: 'DJ', Slug: 'djibouti'},
  {
    Country: 'Holy See (Vatican City State)',
    ISO2: 'VA',
    Slug: 'holy-see-vatican-city-state',
  },
  {Country: 'Libya', ISO2: 'LY', Slug: 'libya'},
  {Country: 'Austria', ISO2: 'AT', Slug: 'austria'},
  {Country: 'Mauritius', ISO2: 'MU', Slug: 'mauritius'},
  {Country: 'Mexico', ISO2: 'MX', Slug: 'mexico'},
  {Country: 'Papua New Guinea', ISO2: 'PG', Slug: 'papua-new-guinea'},
  {Country: 'Saint-Barthélemy', ISO2: 'BL', Slug: 'saint-barthélemy'},
  {Country: 'Slovenia', ISO2: 'SI', Slug: 'slovenia'},
  {
    Country: 'US Minor Outlying Islands',
    ISO2: 'UM',
    Slug: 'us-minor-outlying-islands',
  },
  {Country: 'Greece', ISO2: 'GR', Slug: 'greece'},
  {Country: 'Latvia', ISO2: 'LV', Slug: 'latvia'},
  {Country: 'South Sudan', ISO2: 'SS', Slug: 'south-sudan'},
  {Country: 'Tajikistan', ISO2: 'TJ', Slug: 'tajikistan'},
  {
    Country: 'Turks and Caicos Islands',
    ISO2: 'TC',
    Slug: 'turks-and-caicos-islands',
  },
  {Country: 'Uruguay', ISO2: 'UY', Slug: 'uruguay'},
  {Country: 'Vanuatu', ISO2: 'VU', Slug: 'vanuatu'},
  {Country: 'Czech Republic', ISO2: 'CZ', Slug: 'czech-republic'},
  {Country: 'Congo (Brazzaville)', ISO2: 'CG', Slug: 'congo-brazzaville'},
  {Country: 'Bahrain', ISO2: 'BH', Slug: 'bahrain'},
  {
    Country: 'Central African Republic',
    ISO2: 'CF',
    Slug: 'central-african-republic',
  },
  {Country: 'Hungary', ISO2: 'HU', Slug: 'hungary'},
  {Country: 'Lithuania', ISO2: 'LT', Slug: 'lithuania'},
  {Country: 'Samoa', ISO2: 'WS', Slug: 'samoa'},
  {Country: 'Cameroon', ISO2: 'CM', Slug: 'cameroon'},
  {Country: 'Faroe Islands', ISO2: 'FO', Slug: 'faroe-islands'},
  {Country: 'Singapore', ISO2: 'SG', Slug: 'singapore'},
  {Country: 'Syrian Arab Republic (Syria)', ISO2: 'SY', Slug: 'syria'},
  {Country: 'United States of America', ISO2: 'US', Slug: 'united-states'},
];
